name = "dbest-v1"
pages_build_output_dir = ".vercel/output/static"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# You can put non-secret vars here, but keep Contentful keys in the Dashboard
NODE_VERSION = "22"

[[redirects]]
from = "/hkpl_link"
to = "https://sls.hkpl.gov.hk/digital-collection/tc/collection_hkcee-and-hkale-papers-collection.html"
status = 301

[[redirects]]
from = "/jable"
to = "https://jable.tv/"
status = 301

# Next-on-pages handles most .html redirects automatically, 
# but you can add specific ones back if needed.