name = "dbest-v1"
pages_build_output_dir = ".vercel/output/static"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# You can put non-secret vars here, but keep Contentful keys in the Dashboard
NODE_VERSION = "22"

# Redirects are defined in public/_redirects for CF Pages