// Auto-generated by scripts/extract-page-metadata.js
// Do not edit manually - run the script to update

export interface PageMetadata {
  title: string
  description: string
  robots?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: string
  ogUrl?: string
  ogType?: string
}

export const subjectMetadata: Record<string, PageMetadata> = {
  "bafs": {
    "title": "DSE BAFS 歷屆試題 Past Papers | 企業、會計與財務概論歷屆試題答案",
    "description": "DSE 企業、會計與財務概論 Business, Accounting and Financial Studies 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 評分參考、考生表現報告。提供完整試卷下載，助您全面掌握BAFS考試趨勢及重點。",
    "robots": "index, follow",
    "ogTitle": "DSE BAFS 歷屆試題 Past Papers | 企業、會計與財務概論歷屆試題答案",
    "ogDescription": "DSE 企業、會計與財務概論 Business, Accounting and Financial Studies 歷屆試題下載 (2012-2025)，包含Paper 1A 1B, Paper 2卷一卷二、Answers/Marking Scheme 答案、考生表現報告。提供完整試卷下載，助您全面掌握BAFS考試趨勢及重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/bafs",
    "ogType": "website"
  },
  "biology": {
    "title": "DSE 生物 Biology Past Paper | By Year + By Topic",
    "description": "DSE 生物科 Biology 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Biology考試重點及實驗技巧。",
    "robots": "index, follow",
    "ogTitle": "DSE 生物 Biology 歷屆試題 Past Papers | By Year + By Topic",
    "ogDescription": "DSE 生物科 Biology 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Biology考試重點及實驗技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/biology",
    "ogType": "website"
  },
  "chemistry": {
    "title": "DSE 化學 Chemistry Past Paper | By Year + By Topic",
    "description": "DSE 化學科 Chemistry 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Chemistry實驗技巧及理論知識。",
    "robots": "index, follow",
    "ogTitle": "DSE 化學 Chemistry 歷屆試題 Past Papers | By Year + By Topic",
    "ogDescription": "DSE 化學科 Chemistry 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Chemistry實驗技巧及理論知識。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chemistry",
    "ogType": "website"
  },
  "chinese-history": {
    "title": "DSE 中國歷史 Chinese History Past Paper | 歷屆試題及答案",
    "description": "DSE 中國歷史科歷屆試題及答案。提供完整試卷下載，助您掌握中國歷史科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 中國歷史 Chinese History 歷屆試題 Past Papers | 中國歷史試卷及答案",
    "ogDescription": "DSE 中國歷史科歷屆試題及答案。提供完整試卷下載，助您掌握中國歷史科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chinese-history",
    "ogType": "website"
  },
  "chinese": {
    "title": "DSE 中文 Chinese Past Paper | 閱讀、寫作、聆聽、SBA",
    "description": "DSE 中國語文科 Chinese Language 歷屆試題下載 (2012-2025)，包含 閱讀、寫作、卷一至卷三、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握中文科考試技巧及語文運用能力。",
    "robots": "index, follow",
    "ogTitle": "DSE 中文 Chinese 歷屆試題 Past Papers | 中文卷一至五及答案",
    "ogDescription": "DSE 中國語文科 Chinese Language 歷屆試題下載 (2012-2025)，包含 閱讀、寫作、卷一至卷三、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握中文科考試技巧及語文運用能力。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chinese",
    "ogType": "website"
  },
  "economics": {
    "title": "DSE 經濟 Economics Past Paper | By Year + By Topic",
    "description": "DSE 經濟科 Economics Past Paper 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme。提供完整試卷下載，全面掌握Economics理論應用及分析技巧。",
    "robots": "index, follow",
    "ogTitle": "DSE 經濟 Economics 歷屆試題 Past Papers | 經濟試卷及答案",
    "ogDescription": "DSE 經濟科 Economics Past Paper 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme。提供完整試卷下載，全面掌握Economics理論應用及分析技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/economics",
    "ogType": "website"
  },
  "english": {
    "title": "DSE 英文 English Past Paper | Reading, Listening, Writing, Speaking",
    "description": "DSE 英國語文科 English Language 歷屆試題下載 (2012-2025)，包含Paper 1, Paper 2, Paper 3, Paper 4, Answers/Marking Scheme。提供完整試卷下載，全面提升DSE English語言運用及應試技巧。",
    "robots": "index, follow",
    "ogTitle": "HKDSE 英文 English Past Paper | Reading, Listening, Writing, Speaking",
    "ogDescription": "DSE 英國語文科 English Language 歷屆試題下載(2012-2025)，包含Paper 1, Paper 2, Paper 3, Paper 4, Answers/Marking Scheme。提供完整試卷下載，全面提升DSE English語言運用及應試技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/english",
    "ogType": "website"
  },
  "geography": {
    "title": "DSE 地理 Geography Past Paper | By Topic + By Year",
    "description": "DSE 地理科 Geography 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Geography地圖技能及實地考察技巧。",
    "robots": "index, follow",
    "ogTitle": "DSE 地理 Geography 歷屆試題 Past Papers | By Topic + By Year",
    "ogDescription": "DSE 地理科 Geography 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Geography地圖技能及實地考察技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/geography",
    "ogType": "website"
  },
  "history": {
    "title": "DSE 歷史 History Past Paper | 歷屆試題及答案",
    "description": "DSE 歷史科 History 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握History史料分析及論證技巧。",
    "robots": "index, follow",
    "ogTitle": "DSE 歷史 History 歷屆試題 Past Papers | 歷史試卷及答案",
    "ogDescription": "DSE 歷史科 History 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握History史料分析及論證技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/history",
    "ogType": "website"
  },
  "ict": {
    "title": "DSE 資訊及通訊科技 ICT Past Paper | 歷屆試題及答案",
    "description": "DSE 資訊及通訊科技科 ICT 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握ICT應用技能及解難能力。",
    "robots": "index, follow",
    "ogTitle": "DSE 資訊及通訊科技 ICT 歷屆試題 Past Papers | 資訊及通訊科技試卷及答案",
    "ogDescription": "DSE 資訊及通訊科技科 ICT 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握ICT應用技能及解難能力。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/ict",
    "ogType": "website"
  },
  "m1": {
    "title": "DSE 數學延伸部分 M1 Mathematics Past Paper | By Year + By Topic",
    "description": "DSE 數學延伸部分單元一 Mathematics Extended Part Module 1 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握M1微積分與統計學進階概念。",
    "robots": "index, follow",
    "ogTitle": "DSE 數學延伸部分 M1 Mathematics 歷屆試題 Past Papers | 微積分與統計",
    "ogDescription": "DSE 數學延伸部分單元一 Mathematics Extended Part Module 1 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握M1微積分與統計學進階概念。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/m1",
    "ogType": "website"
  },
  "m2": {
    "title": "DSE 數學延伸部分 M2 Mathematics Past Paper | By Year + By Topic",
    "description": "DSE 數學延伸部分單元二 Mathematics Extended Part Module 2 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握M2代數與微積分進階理論。",
    "robots": "index, follow",
    "ogTitle": "DSE 數學延伸部分 M2 Mathematics 歷屆試題 Past Papers | 代數與微積分",
    "ogDescription": "DSE 數學延伸部分單元二 Mathematics Extended Part Module 2 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握M2代數與微積分進階理論。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/m2",
    "ogType": "website"
  },
  "math": {
    "title": "DSE 數學 Mathematics Past Paper | Paper 1, Paper 2, Answers/Marking Scheme",
    "description": "DSE 數學科 Mathematics 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Mathematics基礎概念及解題技巧。",
    "robots": "index, follow",
    "ogTitle": "DSE 數學 Mathematics 歷屆試題 Past Papers | 數學試卷及答案",
    "ogDescription": "DSE 數學科 Mathematics 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Mathematics基礎概念及解題技巧。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/math",
    "ogType": "website"
  },
  "physics": {
    "title": "DSE 物理 Physics Past Paper | By Year + By Topic",
    "description": "DSE 物理科 Physics 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Physics實驗技能及理論應用能力。",
    "robots": "index, follow",
    "ogTitle": "DSE 物理 Physics 歷屆試題 | By Year + By Topic",
    "ogDescription": "DSE 物理科 Physics 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Physics實驗技能及理論應用能力。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/physics",
    "ogType": "website"
  },
  "visual-arts": {
    "title": "DSE 視覺藝術 Visual Arts Past Paper | 歷屆試題及答案",
    "description": "DSE 視覺藝術科 Visual Arts 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Visual Arts創作技巧及藝術理論知識。",
    "robots": "index, follow",
    "ogTitle": "DSE 視覺藝術 Visual Arts 歷屆試題 Past Papers | 視覺藝術試卷及答案",
    "ogDescription": "DSE 視覺藝術科 Visual Arts 歷屆試題下載 (2012-2025)，包含Paper 1 Paper 2卷一卷二、Answers/Marking Scheme 答案。提供完整試卷下載，全面掌握Visual Arts創作技巧及藝術理論知識。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/visual-arts",
    "ogType": "website"
  },
  "citizen": {
    "title": "DSE 公民與社會發展 Citizenship and Social Development Past Paper | 歷屆試題及答案",
    "description": "DSE 公民與社會發展科 Citizenship and Social Development 歷屆試題下載 (2024-2025)。包含Question Book, Answer Book, Answers 試題簿、及答題簿及答案。提供完整試卷下載，全面掌握公民科考試要點。",
    "robots": "index, follow",
    "ogTitle": "DSE 公民與社會發展 歷屆試題 Past Papers | 公民科試卷及答案",
    "ogDescription": "DSE 公民與社會發展科 Citizenship and Social Development 歷屆試題下載 (2024-2025)。包含Question Book, Answer Book, 試題簿、答題簿及答案。提供完整試卷下載，全面掌握公民科考試要點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/citizen",
    "ogType": "website"
  },
  "ths": {
    "title": "DSE 旅遊與款待 Tourism and Hospitality Past Paper | 歷屆試題及答案",
    "description": "DSE 旅遊與款待科 Tourism and Hospitality Studies 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 評分參考。提供完整試卷下載，全面掌握Tourism and Hospitality行業知識及實務技能。",
    "robots": "index, follow",
    "ogTitle": "DSE 旅遊與款待 Tourism and Hospitality 歷屆試題 Past Papers | 旅遊與款待試卷及答案",
    "ogDescription": "DSE 旅遊與款待科 Tourism and Hospitality Studies 歷屆試題下載 (2012-2025)，包含Paper 1卷一、Answers/Marking Scheme 評分參考。提供完整試卷下載，全面掌握Tourism and Hospitality行業知識及實務技能。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/ths",
    "ogType": "website"
  }
};

export const mainPagesMetadata: Record<string, PageMetadata> = {
  "403": {
    "title": "403 Forbidden",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及公民與社會全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "noindex, nofollow",
    "ogTitle": "403 Forbidden",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及公民與社會等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/403",
    "ogType": "website"
  },
  "404": {
    "title": "404 Not Found",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "noindex, nofollow",
    "ogTitle": "404 Not Found",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/404",
    "ogType": "website"
  },
  "about": {
    "title": "關於 dse.best",
    "description": "關於 dse.best，我們致力於為香港DSE考生提供最優質的學習資源，包括歷屆試題、考試技巧和學習指南。",
    "robots": "index",
    "ogTitle": "關於 dse.best",
    "ogDescription": "關於 dse.best，我們致力於為香港DSE考生提供最優質的學習資源，包括歷屆試題、考試技巧和學習指南。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/about",
    "ogType": "website"
  },
  "homepage": {
    "title": "DSE Past Papers 歷屆試題 | 中文、英文、數學、Phy、Chem、Bio",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index, follow",
    "ogTitle": "DSE Past Papers 歷屆試題 | 中文、英文、數學、Phy、Chem、Bio等",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/",
    "ogType": "website"
  },
  "chat": {
    "title": "dse.best Chatroom",
    "description": "加入dse.best學習社群聊天室，與其他同學即時討論DSE備考心得、學習技巧和考試經驗。支援實時對話、貼圖互動，打造友善的學習交流環境。",
    "robots": "noindex, nofollow",
    "ogTitle": "dse.best Chatroom",
    "ogDescription": "加入dse.best學習社群聊天室，與其他同學即時討論DSE備考心得、學習技巧和考試經驗。支援實時對話、貼圖互動，打造友善的學習交流環境。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chat",
    "ogType": "website"
  },
  "contact": {
    "title": "聯絡我們 Contact Us",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "聯絡我們 Contact Us",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/contact",
    "ogType": "website"
  },
  "countdown": {
    "title": "DSE 2026 Countdown Timer 考試日期倒數",
    "description": "DSE 2026 Countdown Timer 考試日期倒數計時器，幫助香港DSE考生準備文憑試。HKDSE Exam Date Countdown, Study Schedule Planner, Revision Timetable。掌握DSE考試日期，合理安排溫習時間，制定備考策略。How many days left till 2026 DSE Examination?",
    "robots": "index, follow",
    "ogTitle": "DSE 2026 Countdown Timer 考試日期倒數",
    "ogDescription": "DSE 2026 Countdown Timer 考試日期倒數計時器，幫助香港DSE考生準備文憑試。HKDSE Exam Date Countdown, Study Schedule Planner, Revision Timetable。掌握DSE考試日期，合理安排溫習時間，制定備考策略。How many days left till 2026 DSE Examination?",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/countdown",
    "ogType": "website"
  },
  "disclaimer": {
    "title": "免責聲明 Disclaimer",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "免責聲明 Disclaimer",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/disclaimer",
    "ogType": "website"
  },
  "privacy-policy": {
    "title": "私隱政策 Privacy Policy",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "私隱政策 Privacy Policy",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/privacy-policy",
    "ogType": "website"
  },
  "blog": {
    "title": "dse.best Blog | 學習資源、考試技巧、溫習策略、心得分享",
    "description": "DSE Blog 提供2025、2026 DSE考試資訊、中文英文數學物理化學生物ICT M1 M2歷屆試題分析、溫習技巧、考生心得、JUPAS選科攻略、放榜資訊。最新DSE動向、考試趨勢、備考策略、科目指南。",
    "robots": "index, follow",
    "ogTitle": "dse.best Blog | 學習資源、考試技巧、溫習策略、心得分享",
    "ogDescription": "DSE Blog 提供2025、2026 DSE考試資訊、中文英文數學物理化學生物ICT M1 M2歷屆試題分析、溫習技巧、考生心得、JUPAS選科攻略、放榜資訊。最新DSE動向、考試趨勢、備考策略、科目指南。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/blog",
    "ogType": "website"
  },
  "cutoff": {
    "title": "【DSE Cut Off 分數】全港最齊 2012–2025 全部科目等級分界線｜英文、中文、數學等",
    "description": "【DSE Cut Off 分數一覽】全港最齊2012–2025年全部科目等級分界線！涵蓋英文、中文、數學、物理、化學、生物、ICT、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術等。做完past paper？立即對cut off分數，精準預測你嘅DSE Level！",
    "robots": "index, follow",
    "ogTitle": "【DSE Cut Off 分數】全港最齊 2012–2025 全部科目等級分界線｜英文、中文、數學等",
    "ogDescription": "【DSE Cut Off 分數一覽】全港最齊2012–2025年全部科目等級分界線！涵蓋英文、中文、數學、物理、化學、生物、ICT、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術等。做完past paper？立即對cut off分數，精準預測你嘅DSE Level！",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/cutoff",
    "ogType": "website"
  },
  "resources": {
    "title": "DSE 學習資源 Learning Resources | 學習工具、備考指南、NoteSity Discounts",
    "description": "DSE 學習資源中心，提供歷屆試題下載、學習工具、考試技巧、備考策略等全方位學習支援。",
    "robots": "index, follow",
    "ogTitle": "DSE 學習資源 Learning Resources | 學習工具、備考指南、NoteSity Discounts",
    "ogDescription": "DSE 學習資源中心，提供歷屆試題下載、學習工具、考試技巧、備考策略等全方位學習支援。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/resources",
    "ogType": "website"
  },
  "pomodoro": {
    "title": "番茄鐘 Pomodoro Timer | DSE 學習工具",
    "description": "番茄鐘 Pomodoro Timer | DSE 學習工具，幫助DSE學生提高學習效率，合理安排學習和休息時間。採用番茄工作法，25分鐘專注學習，5分鐘休息，提升學習效果。",
    "robots": "index, follow",
    "ogTitle": "番茄鐘 Pomodoro Timer | DSE 學習工具",
    "ogDescription": "番茄鐘 Pomodoro Timer | DSE 學習工具，幫助DSE學生提高學習效率，合理安排學習和休息時間。採用番茄工作法，25分鐘專注學習，5分鐘休息，提升學習效果。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/pomodoro",
    "ogType": "website"
  }
};

export function getPageMetadata(pageKey: string): PageMetadata | null {
  return subjectMetadata[pageKey] || mainPagesMetadata[pageKey] || null;
}

export function getSubjectMetadata(subjectKey: string): PageMetadata | null {
  return subjectMetadata[subjectKey] || null;
}

export function getMainPageMetadata(pageKey: string): PageMetadata | null {
  return mainPagesMetadata[pageKey] || null;
}
