// Auto-generated by scripts/extract-page-metadata.js
// Do not edit manually - run the script to update

export interface PageMetadata {
  title: string
  description: string
  robots?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: string
  ogUrl?: string
  ogType?: string
}

export const subjectMetadata: Record<string, PageMetadata> = {
  "bafs": {
    "title": "DSE BAFS 歷屆試題 Past Papers | 企業、會計與財務概論試卷及答案",
    "description": "DSE BAFS 歷屆試題及答案，涵蓋會計、商業管理、財務管理等課題。提供完整試卷下載，助您掌握商業科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE BAFS 歷屆試題 Past Papers | 企業、會計與財務概論試卷及答案",
    "ogDescription": "DSE BAFS 歷屆試題及答案，涵蓋會計、商業管理、財務管理等課題。提供完整試卷下載，助您掌握商業科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/bafs",
    "ogType": "website"
  },
  "biology": {
    "title": "DSE 生物 Biology Past Paper | 卷一、卷二、評分參考、SBA",
    "description": "DSE 生物 Past Paper | 卷一、卷二、評分參考、SBA - dse.best",
    "robots": "index, follow",
    "ogTitle": "DSE 生物 Biology 歷屆試題 Past Papers | 生物試卷及答案",
    "ogDescription": "DSE 生物 Past Paper | 卷一、卷二、評分參考、SBA - dse.best",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/biology",
    "ogType": "website"
  },
  "chemistry": {
    "title": "DSE 化學 Chemistry Past Paper | 歷屆試題及答案",
    "description": "DSE 化學科歷屆試題及答案，涵蓋無機化學、有機化學、物理化學等課題。提供完整試卷下載，助您掌握化學科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 化學 Chemistry 歷屆試題 Past Papers | 化學試卷及答案",
    "ogDescription": "DSE 化學科歷屆試題及答案，涵蓋無機化學、有機化學、物理化學等課題。提供完整試卷下載，助您掌握化學科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chemistry",
    "ogType": "website"
  },
  "chinese-history": {
    "title": "DSE 中國歷史 Chinese History Past Paper | 歷屆試題及答案",
    "description": "DSE 中國歷史科歷屆試題及答案，涵蓋古代史、近現代史等課題。提供完整試卷下載，助您掌握中國歷史科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 中國歷史 Chinese History 歷屆試題 Past Papers | 中國歷史試卷及答案",
    "ogDescription": "DSE 中國歷史科歷屆試題及答案，涵蓋古代史、近現代史等課題。提供完整試卷下載，助您掌握中國歷史科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chinese-history",
    "ogType": "website"
  },
  "chinese": {
    "title": "DSE 中文 Chinese Past Paper | 閱讀、寫作、聆聽、SBA",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index, follow",
    "ogTitle": "DSE 中文 Chinese 歷屆試題 Past Papers | 中文卷一至五及答案",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chinese",
    "ogType": "website"
  },
  "economics": {
    "title": "DSE 經濟 Economics Past Paper | 歷屆試題及答案",
    "description": "DSE 經濟科歷屆試題及答案，涵蓋微觀經濟學、宏觀經濟學等課題。提供完整試卷下載，助您掌握經濟科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 經濟 Economics 歷屆試題 Past Papers | 經濟試卷及答案",
    "ogDescription": "DSE 經濟科歷屆試題及答案，涵蓋微觀經濟學、宏觀經濟學等課題。提供完整試卷下載，助您掌握經濟科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/economics",
    "ogType": "website"
  },
  "english": {
    "title": "DSE 英文 English Past Paper | Reading, Listening, Writing, Speaking",
    "description": "DSE 英文 English Past Paper 歷屆試題資源，涵蓋Reading, Listening, Writing, Speaking.。",
    "robots": "index, follow",
    "ogTitle": "HKDSE 英文 English Past Paper | Reading, Listening, Writing, Speaking",
    "ogDescription": "DSE 英文 English Past Paper 歷屆試題資源，涵蓋Reading, Listening, Writing, Speaking.。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/english",
    "ogType": "website"
  },
  "geography": {
    "title": "DSE 地理 Geography Past Paper | 歷屆試題及答案",
    "description": "DSE 地理科歷屆試題及答案，涵蓋自然環境、人文環境、全球相互依存等課題。提供完整試卷下載。",
    "robots": "index, follow",
    "ogTitle": "DSE 地理 Geography 歷屆試題 Past Papers | 地理試卷及答案",
    "ogDescription": "DSE 地理科歷屆試題及答案，涵蓋自然環境、人文環境、全球相互依存等課題。提供完整試卷下載。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/geography",
    "ogType": "website"
  },
  "history": {
    "title": "DSE 歷史 History Past Paper | 歷屆試題及答案",
    "description": "DSE 歷史科歷屆試題及答案，涵蓋現代世界、現代中國等課題。提供完整試卷下載，助您掌握歷史科考試重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 歷史 History 歷屆試題 Past Papers | 歷史試卷及答案",
    "ogDescription": "DSE 歷史科歷屆試題及答案，涵蓋現代世界、現代中國等課題。提供完整試卷下載，助您掌握歷史科考試重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/history",
    "ogType": "website"
  },
  "ict": {
    "title": "DSE 資訊及通訊科技 ICT Past Paper | 歷屆試題及答案",
    "description": "DSE ICT 歷屆試題及答案，涵蓋資訊處理、程式編寫、數據庫、網絡等課題。提供完整試卷下載。",
    "robots": "index, follow",
    "ogTitle": "DSE 資訊及通訊科技 ICT 歷屆試題 Past Papers | 資訊及通訊科技試卷及答案",
    "ogDescription": "DSE ICT 歷屆試題及答案，涵蓋資訊處理、程式編寫、數據庫、網絡等課題。提供完整試卷下載。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/ict",
    "ogType": "website"
  },
  "m1": {
    "title": "DSE 數學延伸部分 M1 Mathematics Past Paper | 歷屆試題及答案",
    "description": "DSE 數學延伸部分 M1 (微積分與統計) 歷屆試題及答案。提供完整試卷下載，助您掌握微積分與統計學重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 數學延伸部分 M1 Mathematics 歷屆試題 Past Papers | 微積分與統計",
    "ogDescription": "DSE 數學延伸部分 M1 (微積分與統計) 歷屆試題及答案。提供完整試卷下載，助您掌握微積分與統計學重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/m1",
    "ogType": "website"
  },
  "m2": {
    "title": "DSE 數學延伸部分 M2 Mathematics Past Paper | 歷屆試題及答案",
    "description": "DSE 數學延伸部分 M2 (代數與微積分) 歷屆試題及答案。提供完整試卷下載，助您掌握代數與微積分重點。",
    "robots": "index, follow",
    "ogTitle": "DSE 數學延伸部分 M2 Mathematics 歷屆試題 Past Papers | 代數與微積分",
    "ogDescription": "DSE 數學延伸部分 M2 (代數與微積分) 歷屆試題及答案。提供完整試卷下載，助您掌握代數與微積分重點。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/m2",
    "ogType": "website"
  },
  "math": {
    "title": "DSE 數學 Mathematics Past Paper",
    "description": "DSE 數學 Mathematics Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index, follow",
    "ogTitle": "HKDSE 數學 Mathematics Past Paper",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/math",
    "ogType": "website"
  },
  "physics": {
    "title": "DSE 物理 Physics Past Paper",
    "description": "DSE 物理 Physics Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index, follow",
    "ogTitle": "DSE 物理 Physics 歷屆試題 Past Papers | 物理試卷及答案",
    "ogDescription": "DSE 物理 Physics Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/physics",
    "ogType": "website"
  },
  "visual-arts": {
    "title": "DSE 視覺藝術 Visual Arts Past Paper | 歷屆試題及答案",
    "description": "下載DSE視覺藝術科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供2012-2024年完整試卷。",
    "robots": "noindex, nofollow",
    "ogTitle": "DSE 視覺藝術 Visual Arts 歷屆試題 Past Papers | 視覺藝術試卷及答案",
    "ogDescription": "下載DSE視覺藝術科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供2012-2024年完整試卷。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/visual-arts",
    "ogType": "website"
  },
  "citizen": {
    "title": "DSE 公民與社會發展 Citizenship and Social Development Past Paper | 歷屆試題及答案",
    "description": "下載DSE公民與社會發展科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供完整試卷。",
    "robots": "noindex, nofollow",
    "ogTitle": "DSE 公民與社會發展 歷屆試題 Past Papers | 公民科試卷及答案",
    "ogDescription": "下載DSE公民與社會發展科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供完整試卷。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/citizen",
    "ogType": "website"
  },
  "ths": {
    "title": "DSE 旅遊與款待 Tourism and Hospitality Studies Past Paper | 歷屆試題及答案",
    "description": "下載DSE旅遊與款待科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供2012-2023年完整試卷。",
    "robots": "index, follow",
    "ogTitle": "DSE 旅遊與款待 Tourism and Hospitality Studies 歷屆試題 Past Papers | 旅遊與款待試卷及答案",
    "ogDescription": "下載DSE旅遊與款待科歷屆試題、答案及考生表現，全面掌握考試趨勢，提升應考實力。免費提供2012-2023年完整試卷。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/ths",
    "ogType": "website"
  }
};

export const mainPagesMetadata: Record<string, PageMetadata> = {
  "403": {
    "title": "403 Forbidden",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "noindex, nofollow",
    "ogTitle": "403 Forbidden",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/403",
    "ogType": "website"
  },
  "404": {
    "title": "404 Not Found",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "noindex, nofollow",
    "ogTitle": "404 Not Found",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/404",
    "ogType": "website"
  },
  "about": {
    "title": "關於 dse.best",
    "description": "DSEBest 介紹 - 我們是一群熱衷於教育的專業人士，致力於為香港DSE考生提供最優質的學習資源，包括歷屆試題、考試技巧和學習指南。",
    "robots": "index",
    "ogTitle": "關於 dse.best",
    "ogDescription": "認識 DSEBest 團隊 - 我們由教育專家和前DSE考生組成，致力於為香港學生提供最全面的DSE備考資源和支援。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/about",
    "ogType": "website"
  },
  "homepage": {
    "title": "HKDSE Past Papers 歷屆試題 | 中文、英文、數學、Phy、Chem、Bio、M1/M2等",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index, follow",
    "ogTitle": "HKDSE Past Papers 歷屆試題 | 中文、英文、數學、Phy、Chem、Bio、M1/M2等",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/",
    "ogType": "website"
  },
  "chat": {
    "title": "Chatroom 聊天室",
    "description": "DSE Best學習交流聊天室，與其他同學一起討論學習心得，分享DSE備考經驗。",
    "robots": "noindex, nofollow",
    "ogTitle": "Chatroom 聊天室",
    "ogDescription": "DSE Best學習交流聊天室，與其他同學一起討論學習心得，分享DSE備考經驗。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/chat",
    "ogType": "website"
  },
  "contact": {
    "title": "聯絡我們 Contact Us",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "聯絡我們 Contact Us",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/contact",
    "ogType": "website"
  },
  "countdown": {
    "title": "DSE 2026 Countdown Timer 考試日期倒數",
    "description": "DSE倒數計時器，幫助你準備文憑試。掌握DSE考試日期，合理安排溫習時間。",
    "robots": "index, follow",
    "ogTitle": "DSE 2026 Countdown Timer 考試日期倒數",
    "ogDescription": "DSE倒數計時器，幫助你準備文憑試。掌握DSE考試日期，合理安排溫習時間。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/countdown",
    "ogType": "website"
  },
  "disclaimer": {
    "title": "免責聲明 Disclaimer",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "免責聲明 Disclaimer",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/disclaimer",
    "ogType": "website"
  },
  "privacy-policy": {
    "title": "私隱政策 Privacy Policy",
    "description": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、M1/M2、地理、歷史、中國歷史、經濟及視覺藝術全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "robots": "index",
    "ogTitle": "私隱政策 Privacy Policy",
    "ogDescription": "DSE Past Paper 歷屆試題資源，涵蓋中文、英文、數學、物理、化學、ICT、BAFS、生物、數學延伸部分 (M1 和 M2)、地理、歷史、中國歷史、經濟及視覺藝術等全科歷屆試題及答案，支援按科目及年份搜尋，助你掌握DSE考試趨勢。2025、2026 DSE放榜日期、DSE cut off分數、成績查詢、JUPAS資訊等最新資訊一應俱全。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/privacy-policy",
    "ogType": "website"
  },
  "blog": {
    "title": "dse.best Blog | 學習資源、考試技巧、溫習策略、心得分享",
    "description": "DSE Blog 提供2025、2026 DSE考試資訊、中文英文數學物理化學生物ICT M1 M2歷屆試題分析、溫習技巧、考生心得、JUPAS選科攻略、放榜資訊。最新DSE動向、考試趨勢、備考策略、科目指南。",
    "robots": "index, follow",
    "ogTitle": "dse.best Blog | 學習資源、考試技巧、溫習策略、心得分享",
    "ogDescription": "DSE Blog 提供2025、2026 DSE考試資訊、中文英文數學物理化學生物ICT M1 M2歷屆試題分析、溫習技巧、考生心得、JUPAS選科攻略、放榜資訊。最新DSE動向、考試趨勢、備考策略、科目指南。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/blog",
    "ogType": "website"
  },
  "cutoff": {
    "title": "DSE Cut off Scores (2012-2024)",
    "description": "HKDSE 各科目等級Cut Off查詢，包括中文、英文、數學、物理、化學、生物、ICT、M1、M2等科目的歷年Cut Off資料。了解各等級達標分數，助您制定備考策略。",
    "robots": "index, follow",
    "ogTitle": "HKDSE Cut-off Scores (2012-2024)",
    "ogDescription": "HKDSE 各科目等級分數Cut Off查詢，包括中文、英文、數學、物理、化學、生物、ICT、M1、M2等科目的歷年Cut Off資料。了解各等級達標分數，助您制定備考策略。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/cutoff",
    "ogType": "website"
  },
  "resources": {
    "title": "DSE 學習資源 Learning Resources | 歷屆試題、學習工具、備考指南",
    "description": "DSE 學習資源中心，提供歷屆試題下載、學習工具、考試技巧、備考策略等全方位學習支援。涵蓋中文、英文、數學、物理、化學、生物等全科資源。",
    "robots": "index, follow",
    "ogTitle": "DSE 學習資源 Learning Resources | 歷屆試題、學習工具、備考指南",
    "ogDescription": "DSE 學習資源中心，提供歷屆試題下載、學習工具、考試技巧、備考策略等全方位學習支援。涵蓋中文、英文、數學、物理、化學、生物等全科資源。",
    "ogImage": "https://dse.best/assets/images/logo-icon.png",
    "ogUrl": "https://dse.best/resources",
    "ogType": "website"
  }
};

export function getPageMetadata(pageKey: string): PageMetadata | null {
  return subjectMetadata[pageKey] || mainPagesMetadata[pageKey] || null;
}

export function getSubjectMetadata(subjectKey: string): PageMetadata | null {
  return subjectMetadata[subjectKey] || null;
}

export function getMainPageMetadata(pageKey: string): PageMetadata | null {
  return mainPagesMetadata[pageKey] || null;
}
